#
# This file contains configuration flags to customize your site
#

# Name of your site (displayed in the header)
name: ReviewHuntr

# Short bio or description (displayed in the header)
description: The best reviews of everything. Ever.
description-long: | 
  ReviewHuntr helps you find the best reviews on the internet. You'll find product reviews for electronics, computers, home appliances, and many other things you might not expect. ReviewHuntr will help you find the best reviews.
# URL of your avatar or profile pic (you could use your GitHub profile pic)
avatar: /images/logo/MediumSquareLogo.jpg

defaults:
  -
    scope:
      path: ""
      type: "posts" # previously `page` in Jekyll 2.2.
    values:
      author: "ReviewHuntr"

#
# Flags below are optional
#

# Includes an icon in the footer for each username you enter
footer-links:
  dribbble:
  email:
  facebook:
  flickr:
  github: 
  instagram:
  linkedin:
  pinterest:
  rss: yea
  twitter: 
  stackoverflow: # your stackoverflow profile, e.g. "users/50476/bart-kiers"
  youtube: 
  discord: uEBWZKq
  patreon: 
  googleplus: # anything in your profile username that comes after plus.google.com/


# Enter your Disqus shortname (not your username) to enable commenting on posts
# You can find your shortname on the Settings page of your Disqus account
disqus:

github:
  repository_url: https://github.com/MrPowerScripts/reviewhuntr

# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
google_analytics: UA-121890486-4

# Your website URL (e.g. http://barryclark.github.io or http://www.barryclark.co)
# Used for Sitemap.xml and your RSS feed
url: https://reviewhuntr.com

# If you're hosting your site at a Project repository on GitHub pages
# (http://yourusername.github.io/repository-name)
# and NOT your User repository (http://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
baseurl: ""

#
# !! You don't need to change any of the configuration flags below !!
#

permalink: /:title/

# The release of Jekyll Now that you're using
version: v1.2.0

# Jekyll 3 now only supports Kramdown for Markdown
kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
    css_class: 'highlight'

collections:
  posts:
    output: true
  reviews:
    output: true
    permalink: /reviews/:title/

# Pagination stuff using v2 now
pagination:
  enabled: true
  per_page: 5
  permalink: "/page-:num/"
  sort_field: 'date'
  collection: 'posts'
  sort_reverse: true
  trail: 
    before: 2
    after: 2

autopages:
  # Site-wide kill switch, disable here and it doesn't run at all 
  enabled: true

  # Category pages, omit entire config element to disable
  categories: 
    # Optional, the list of layouts that should be processed for every category found in the site
    layouts: 
      - 'auto_category.html'
    # Optional, the title that each category paginate page should get (:cat is replaced by the Category name)
    title: 'Posts in category :cat'
    # Optional, the permalink for the  pagination page (:cat is replaced), 
    # the pagination permalink path is then appended to this permalink structure
    permalink: '/category/:cat'

  # Collection pages, omit to disable
  collections:
    layouts: 
      - 'auto_collection.html'
    title: 'Posts in collection :coll' # :coll is replaced by the collection name
    permalink: '/collection/:coll'
  
  # Tag pages, omit to disable
  tags:
    layouts: 
      - 'auto_tag.html'
    title: 'Posts tagged with :tag' # :tag is replaced by the tag name
    permalink: '/tag/:tag'

# Set the Sass partials directory, as we're using @imports
sass:
  style: :expanded # You might prefer to minify using :compressed

# Use the following plug-ins
plugins:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem
  - jekyll-paginate-v2 #pagination!

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - vendor/bundle
